// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-day.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-day.ts
var get_day_default = defineTool({
  name: "get_day",
  title: "Ver h\xE1bitos do dia",
  description: "Retorna os h\xE1bitos registrados (\xE1gua, exerc\xEDcio, estudo, leitura) do usu\xE1rio autenticado em uma data espec\xEDfica (YYYY-MM-DD).",
  inputSchema: {
    date: z.string().describe("Data no formato YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daily_habits").select("*").eq("user_id", ctx.getUserId()).eq("date", date).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: `Nenhum registro para ${date}.` }],
        structuredContent: { date, record: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { date, record: data }
    };
  }
});

// src/lib/mcp/tools/list-days.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_days_default = defineTool2({
  name: "list_days",
  title: "Listar hist\xF3rico de h\xE1bitos",
  description: "Lista os registros di\xE1rios de h\xE1bitos do usu\xE1rio autenticado dentro de um intervalo de datas (YYYY-MM-DD).",
  inputSchema: {
    start_date: z2.string().describe("Data inicial no formato YYYY-MM-DD."),
    end_date: z2.string().describe("Data final no formato YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daily_habits").select("*").eq("user_id", ctx.getUserId()).gte("date", start_date).lte("date", end_date).order("date", { ascending: true }).limit(400);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { days: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-habit.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var log_habit_default = defineTool3({
  name: "log_habit",
  title: "Registrar h\xE1bito do dia",
  description: "Registra ou atualiza os h\xE1bitos do usu\xE1rio autenticado numa data: \xE1gua (ml), exerc\xEDcio, estudo e leitura (conclu\xEDdo ou justificado).",
  inputSchema: {
    date: z3.string().describe("Data no formato YYYY-MM-DD."),
    water_ml: z3.number().optional().describe("Total de \xE1gua bebida no dia, em ml."),
    exercise_done: z3.boolean().optional(),
    exercise_justified: z3.boolean().optional(),
    study_done: z3.boolean().optional(),
    study_justified: z3.boolean().optional(),
    reading_done: z3.boolean().optional(),
    reading_justified: z3.boolean().optional(),
    day_completed: z3.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const updates = Object.fromEntries(
      Object.entries(fields).filter(([, value]) => value !== void 0)
    );
    if (Object.keys(updates).length === 0) {
      throw new ToolError("Informe ao menos um campo de h\xE1bito para registrar.");
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daily_habits").upsert({ user_id: ctx.getUserId(), date, ...updates }, { onConflict: "user_id,date" }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { record: data }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_profile_default = defineTool4({
  name: "get_profile",
  title: "Ver perfil e pontos",
  description: "Retorna o perfil do usu\xE1rio autenticado (nickname, meta de \xE1gua, incremento) e o saldo de pontos acumulados.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profileRes, pointsRes] = await Promise.all([
      supabase.from("profiles").select("display_name, water_goal_ml, water_increment_ml, age, height_cm, weight_kg").eq("user_id", userId).maybeSingle(),
      supabase.from("user_points").select("balance, total_earned, total_spent").eq("user_id", userId).maybeSingle()
    ]);
    if (profileRes.error) {
      return { content: [{ type: "text", text: profileRes.error.message }], isError: true };
    }
    const payload = { profile: profileRes.data, points: pointsRes.data ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eascltdhoephvzwphtih";
var mcp_default = defineMcp({
  name: "by",
  title: "BY",
  version: "0.1.0",
  instructions: "Ferramentas do BY (Better You), um app de acompanhamento de h\xE1bitos em portugu\xEAs. Use `get_profile` para o perfil e pontos, `get_day` e `list_days` para consultar h\xE1bitos (\xE1gua, exerc\xEDcio, estudo, leitura) e `log_habit` para registrar ou atualizar o dia. Datas sempre no formato YYYY-MM-DD, no fuso local do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, get_day_default, list_days_default, log_habit_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
